name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the gateway Docker image
      run: docker build . --file gateway/Tasky.Gateway/Dockerfile --tag task-gateway:$(date +%s)
